server.port=8080
spring.application.name=api-gateway

# Rutas dinámicas: si mañana cambias de servidor, no editas el código, cambias la variable
spring.cloud.gateway.mvc.routes[0].id=iam-service
spring.cloud.gateway.mvc.routes[0].uri=${IAM_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.mvc.routes[1].id=core-service
spring.cloud.gateway.mvc.routes[1].uri=${CORE_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/tickets/**