spring.application.name=core-service
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.compatibility-verifier.enabled=false
// Configuración para manejar archivos grandes (si es necesario)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB