# Puerto universal por defecto para el Config Server
server.port=8888
spring.application.name=config-server

# Perfil activo para el Config Server, utilizando el perfil 'native' para leer archivos de configuración desde el sistema de archivos local
spring.profiles.active=native

# La ruta exacta hacia la carpeta 'config-repo' donde se encuentran los archivos de configuración
spring.cloud.config.server.native.search-locations=file:///C:/Users/C4R1/Desktop/UTP/CICLOS/CICLO 9 - V2/Integrador 2/proyecto_SATSIW/config-repo